{
	"responseHeader":
	{
		"status":0,
		"QTime":0,
		"params":
		{
			"q":"freio",
			"indent":"true",
			"wt":"json"
		}
	},
	"response":{
		"numFound":5,
		"start":0,
		"docs":
		[{
			"id":"/home/dismo/Desktop/solr-5.1.0/example/patentes/Patente_CodPedido_968416.html",
			"stream_size":[54963],
			"x_parsed_by":
			[
				"org.apache.tika.parser.DefaultParser",
				"org.apache.tika.parser.html.HtmlParser"
			],
			"stream_content_type":["text/html"],
			"dc_title":["INPI"],
			"content_encoding":["ISO-8859-1"],
			"resourcename":["/home/dismo/Desktop/solr-5.1.0/example/patentes/Patente_CodPedido_968416.html"],
			"title":["INPI"],
			"content_type":["text/html; charset=ISO-8859-1"],
			"_version_":1504243745869004800
		},
		{
			"id":"/home/dismo/Desktop/solr-5.1.0/example/patentes/Patente_CodPedido_968416.html",
			"stream_size":[54963],
			"x_parsed_by":
			[
				"org.apache.tika.parser.DefaultParser",
				"org.apache.tika.parser.html.HtmlParser"
			],
			"stream_content_type":["text/html"],
			"dc_title":["INPI"],
			"content_encoding":["ISO-8859-1"],
			"resourcename":["/home/dismo/Desktop/solr-5.1.0/example/patentes/Patente_CodPedido_968416.html"],
			"title":["INPI"],
			"content_type":["text/html; charset=ISO-8859-1"],
			"_version_":1504243745869004800
		},
		{
			"id":"/home/dismo/Desktop/solr-5.1.0/example/patentes/Patente_CodPedido_968416.html",
			"stream_size":[54963],
			"x_parsed_by":
			[
				"org.apache.tika.parser.DefaultParser",
				"org.apache.tika.parser.html.HtmlParser"
			],
			"stream_content_type":["text/html"],
			"dc_title":["INPI"],
			"content_encoding":["ISO-8859-1"],
			"resourcename":["/home/dismo/Desktop/solr-5.1.0/example/patentes/Patente_CodPedido_968416.html"],
			"title":["INPI"],
			"content_type":["text/html; charset=ISO-8859-1"],
			"_version_":1504243745869004800
		},
		{
			"id":"/home/dismo/Desktop/solr-5.1.0/example/patentes/Patente_CodPedido_968416.html",
			"stream_size":[54963],
			"x_parsed_by":
			[
				"org.apache.tika.parser.DefaultParser",
				"org.apache.tika.parser.html.HtmlParser"
			],
			"stream_content_type":["text/html"],
			"dc_title":["INPI"],
			"content_encoding":["ISO-8859-1"],
			"resourcename":["/home/dismo/Desktop/solr-5.1.0/example/patentes/Patente_CodPedido_968416.html"],
			"title":["INPI"],
			"content_type":["text/html; charset=ISO-8859-1"],
			"_version_":1504243745869004800
		},
		{
			"id":"/home/dismo/Desktop/solr-5.1.0/example/patentes/Patente_CodPedido_968416.html",
			"stream_size":[54963],
			"x_parsed_by":
			[
				"org.apache.tika.parser.DefaultParser",
				"org.apache.tika.parser.html.HtmlParser"
			],
			"stream_content_type":["text/html"],
			"dc_title":["INPI"],
			"content_encoding":["ISO-8859-1"],
			"resourcename":["/home/dismo/Desktop/solr-5.1.0/example/patentes/Patente_CodPedido_968416.html"],
			"title":["INPI"],
			"content_type":["text/html; charset=ISO-8859-1"],
			"_version_":1504243745869004800
		}
		]
  	}
}
